name: yearn-v3

plugins:
  - name: solidity
  - name: vyper
  - name: hardhat

default_ecosystem: ethereum
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.6.0

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.6.0"

ethereum:
  local:
    default_provider: hardhat
